// FIRST NAMES - ENGLISH
var engs = [
["Emily","Michelle","Mandy","Amber","Kelly","Angel","Cherry","Heidi","Alice","Athena","Kate","Charlotte","Jennifer","Christine","Janet","Lily","Sandy","Natalie","Joyce","Ring","Sierra","Catherine","Zoe","Sarah","Iris","Janice","Ariel","Nicole","Celia","Andree","Carly","Daania","Alison","Ashley","Noel","Stella","Wendy","Christy","Evelyn","Carmen","Tracy","Cleo","Yuki","Amelia","Hayley","Karen","Melissa","Joey","Rachel","Koie","Ally","Karman","Ailsha","Ann","Shiny","Shane","Maxine","Yumi","Sapphire","Niya","Kary","Cherrie","Mindy","Lucy","Unice","Akane","Pinky","Rosie","Jojo","Jang","Selina","Ka","Yoanna","Edria","Venus","Carina","Angela","Bernice","Stephanie","Kane","Bobo","Serina","Candy","Marketa","Sabrina","Misa","Jaime","Regina","Kitty","May","Delinna"], 
["Jason","Kenneth","Lucas","Eric","Marco","Renaud","Ricotta","William","Jamie","Chase","Ryan","Tom","Anthony","Elijah","Weaton","Mack","Jackson","Jack","Davis","Nikita","Keith","Tobias","Heyson","Harvey","Ellis","Thomas","Matthew","Trevor","Victor","Han","Bowie","Mark","Ross","Brian","Jerry","Ernest","Marcus","Watson","Irving","Ericford","Arthur","Cedric","Jordan","Win","Vincent","Yu","Charlie","Horis","Bruce","Bikas","Peter","Abel","Jay","Kyle","Sam","Cora","Archibald","Edwin","Taiga","Timmy","Eric","Chiba","Kendrick","Hubert","Darren","Simon","Aaron","Oscar","Roy","Vic","Argo","Jonathan","Alan","Louis","Patrick","Kennyon","Seol","Billy","Henry"]];


// FIRST NAMES - CANTONESE
var firsts = [
["Ka Yee","Yin Kwan","Wai Yi","Yee Hang","Tsam Yui","Tsz Shan","Ka Po","Yu Ting","Chui Yin","Wing Ki","Pui Chi","Tsz Yan","Tsz Ki","Po Yi","Heung To","Kam Ting","Wai Yuk","Hiu Lam","Tsz Man","Ka Yin","Tze Wun","Man Tung","Tzu Yi","Tsz Shan","Wing Shun","Fung Yi","Yi Nei","Cho Lam","Tsz Wai","Wing Sze","Wing Hei","Ka Tung","Wing Sum","Tsz Lok","Man Siu","Tan Ling","Wai Lam","Lok Yi","Mei Yan","Man Wai","Wai Yi","Hiu Ying","Suet Yi","Ching Chi","Wing Sze","Sze Man","Wai Han","Wing Yan","Wing Yan","Tsz Han","Hoi Ting","Yu Sum","Man Nam","Tsz Tung","Ka Yu","Hau Yi","Ka Ki","Ka Wai","Sze Ki","Wing Yi","Man Tan","Tsz Ching","Ka Yee","Tak Wai","Hoi Ki","Shu Kiu","Ka Lam","Wan Sze","Fung Ming","Hiu Laam"], 
["Man Hei","Wing Tat","Yat Ching","Ho Yin","Wang Kei","Kan Chau","Chak Yuen","Hiu Wai","Kin Hei","Siu Hong","Tsz Nok","Wing Nam","Man Tim","Chong Ho","Chau Yin","Wai Nok","Ka Wing","Tik Kwan","Tsz Chun","Pak Chun","Tsz Yau","Ho Ming","Pui Ham","Tsun Hin","Chung Ho","Chin Pang","Kwun Wa","Hin Ki","Kin Hei","Hing Fung","Chun Fung","Man Kit","Siu Lung","Chi Ho","Chi Lai","Ka Ho","Ka Yuet","Pok Chi","Mun Ting","Man Ki","Cheuk Yin","Yiu Man","Hon Yin","Wai Chau","Ho Man","Yiu Hong","Ho Seng","Ho Yuen","Ho Man","Hoi Dik","Chi Hang","Ka Yut","Tik Ho","Yuen Fong","Chung Yin","Ip To","Kan Kuen","Yu Hin","Chun Chak","Ka Lok","Cheuk Kiu","Yim Lung","Yik Ki","Ho Fai","Ka Kit","Chiu Lung","Chak Sing","Ka Chun","Man Kit","Chun Kit"]];


// LAST NAMES - CANTONESE
var lasts = ["Chan","Cheng","Cheung","Chiu","Chow","Chau","Hung","Ip","Yip","Kwan","Lam","Lau","Lai","Lee","Li","Leung","Liu","Lo","Ng","Poon","Pun","So","Siu","Tam","Tsang","Yau","Yiu","Yu","Wong"];